# Lecture1; Tutorial

### Check your Tensorflow version

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.2.0


2.12.0


### Tensor와 친해지기

In [ ]:
t = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
tensor = tf.constant(t)

print(tensor)
print("shape:", tf.shape(tensor))
print("size:", tf.size(tensor))
print("rank:", tf.rank(tensor)) #rank:1 -> vector, 2: matrix, 3: cube

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12], shape=(12,), dtype=int32)

shape: tf.Tensor([12], shape=(1,), dtype=int32)
size: tf.Tensor(12, shape=(), dtype=int32)
rank: tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
t1 = [1, 2, 3]
print(type(t1))
t2 = [3, 4, 5]
print(t1+t2)
t1 = tf.constant(t1)
t2 = tf.constant(t2)
print(t1 + t2)


<class 'list'>
[1, 2, 3, 3, 4, 5]
tf.Tensor([4 6 8], shape=(3,), dtype=int32)


In [ ]:
def print_ssr(tensor):
    print(tensor)
    print()
    print("shape:", tf.shape(tensor))
    print("size:", tf.size(tensor))
    print("rank:", tf.rank(tensor))

In [ ]:
tensor2d = tf.reshape(tensor, [3,4])
print_ssr(tensor2d)

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)

shape: tf.Tensor([3 4], shape=(2,), dtype=int32)
size: tf.Tensor(12, shape=(), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
print(tensor2d[1]) #print(tensor2d[1,:])와 똑같은 의미
print(tensor2d[1,2])

tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)


In [ ]:
tensor3d=tf.reshape(tensor, [3,2,2])
print_ssr(tensor3d)

tf.Tensor(
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]], shape=(3, 2, 2), dtype=int32)

shape: tf.Tensor([3 2 2], shape=(3,), dtype=int32)
size: tf.Tensor(12, shape=(), dtype=int32)
rank: tf.Tensor(3, shape=(), dtype=int32)


In [ ]:
tensor3d=tf.reshape(tensor, [3,1,4])
print_ssr(tensor3d)

tf.Tensor(
[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]], shape=(3, 1, 4), dtype=int32)

shape: tf.Tensor([3 1 4], shape=(3,), dtype=int32)
size: tf.Tensor(12, shape=(), dtype=int32)
rank: tf.Tensor(3, shape=(), dtype=int32)


In [ ]:
tensor3d=tf.reshape(tensor, [1,3,4])
print_ssr(tensor3d)

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]], shape=(1, 3, 4), dtype=int32)

shape: tf.Tensor([1 3 4], shape=(3,), dtype=int32)
size: tf.Tensor(12, shape=(), dtype=int32)
rank: tf.Tensor(3, shape=(), dtype=int32)


### tf.squeeze, tf.expand_dims 사용해서 행렬곱 계산하기

*   항목 추가
*   항목 추가



In [ ]:
x = tf.constant([1, 0, -1, 1])
print_ssr(x)

tf.Tensor([ 1  0 -1  1], shape=(4,), dtype=int32)

shape: tf.Tensor([4], shape=(1,), dtype=int32)
size: tf.Tensor(4, shape=(), dtype=int32)
rank: tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
tf.matmul(tensor3d,x) #차원이 맞지 않아서 오류 발생

InvalidArgumentError: In[1] ndims must be >= 2: 1 [Op:BatchMatMulV2]

In [ ]:
tensor3d = tf.squeeze(tensor3d)
print(tensor3d)

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)


In [ ]:
x_0 = tf.expand_dims(x,0)
print(x_0)

tf.Tensor([[ 1  0 -1  1]], shape=(1, 4), dtype=int32)


In [ ]:
x_1 = tf.expand_dims(x,1)
print(x_1)

tf.Tensor(
[[ 1]
 [ 0]
 [-1]
 [ 1]], shape=(4, 1), dtype=int32)


In [ ]:
tf.matmul(tensor3d,x_1)

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[ 2],
       [ 6],
       [10]], dtype=int32)>

In [ ]:
print(tensor3d@x_1)

tf.Tensor(
[[ 2]
 [ 6]
 [10]], shape=(3, 1), dtype=int32)


### tf.reduce_sum, tf.reduce_mean의 의미 이해하기

In [ ]:
mat = tf.constant([[1.0, 2.0],[3.0, 4.0]])

my_sum = tf.reduce_sum(mat)
my_mean = tf.reduce_mean(mat)
print(my_sum)
print(my_mean)

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor(2.5, shape=(), dtype=float32)


In [ ]:
print(tf.reduce_mean(mat, 0))
print(tf.reduce_mean(mat, 1))
print(tf.reduce_sum(mat, 0))
print(tf.reduce_sum(mat, 1))

tf.Tensor([2. 3.], shape=(2,), dtype=float32)
tf.Tensor([1.5 3.5], shape=(2,), dtype=float32)
tf.Tensor([4. 6.], shape=(2,), dtype=float32)
tf.Tensor([3. 7.], shape=(2,), dtype=float32)


### tf.Variable로 텐서 변수 선언해보기

In [ ]:
mat1 = tf.constant([[1.0, 2.0],[3.0, 4.0]])
mat2 = tf.Variable([[1.0, 2.0],[3.0, 4.0]])

print(mat1)
print(mat2)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>
